# 5. Numpy

In [3]:
import numpy as np

In [4]:
a=np.array([np.arange(6)]*6)+np.arange(0,51,10).reshape(6,1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [7]:
a[0,3:5]

array([3, 4])

In [9]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [15]:
a[0:,2]

array([ 2, 12, 22, 32, 42, 52])

In [16]:
a[0:,2:3]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

In [19]:
a[0:,2]=[1,2,3,4,5,6]
a

array([[ 0,  1,  1,  3,  4,  5],
       [10, 11,  2, 13, 14, 15],
       [20, 21,  3, 23, 24, 25],
       [30, 31,  4, 33, 34, 35],
       [40, 41,  5, 43, 44, 45],
       [50, 51,  6, 53, 54, 55]])

In [20]:
a[2::2,0:6:2]

array([[20,  3, 24],
       [40,  5, 44]])